#!/bin/bash

# Install sudo
apt-get install -y sudo

# Setup user
passwd -d root
groupadd me
useradd  -g me me
passwd -d me
echo -e "\nme ALL=(ALL) NOPASSWD: ALL\n" | tee -a /etc/sudoers
sed -i "/secure_path/c\Defaults secure_path=\"$PATH\"" /etc/sudoers
mkdir -p /home/me 
