#!/bin/bash

# Install sudo
apt-get install -y sudo

# Setup user
passwd -d root
groupadd me
useradd  -g me me
passwd -d me
echo "\nme ALL=(ALL) NOPASSWD: ALL\n" >> /etc/sudoers && cat /etc/sudoers
sed -i "/secure_path/c\Defaults secure_path=\"$PATH\"" /etc/sudoers
mkdir -p /home/me 
