#!/bin/bash

# Cleanup modules
for module in ${DOCKER_MODULES[@]}; do
	script="/docker/scripts/modules/${module}/cleanup"
	if [ -f "$script" ]; then
		echo "Performing cleanup for $module"
		"$script"
	fi
done