#!/bin/bash

# Entry required modules
for module in ${BUILD_MODULES[@]}; do
	script="/docker/scripts/modules/${module}/entry"
	if [ -f "$script" ]; then
		echo "Setupping $module entry"
		"$script"
	fi
done

# Entry configuration files
shopt -s nullglob
for filename in /docker/etc/entry.d/*; do
	(chmod +x "$filename" && "$filename")
done

# Execute command
sudo -i -H -u me -- $@