#!/bin/bash

# Run as sudo
if [ "$(id -u)" != "0" ]; then
	exec sudo -H -E -- "$0" "$*"
fi

# Entry required modules
for module in ${BUILD_MODULES[@]}; do
	script="/docker/scripts/modules/${module}/entry"
	if [ -f "$script" ]; then
		echo "Setupping $module entry"
		"$script"
	fi
done

# Entry configuration files
shopt -s nullglob
for filename in /docker/etc/entry.d/*; do
	(chmod +x "$filename" && "$filename")
done

# Execute command
echo "Running '$@'"
sudo -i -H -E -u me -- $@