#!/bin/bash

# Setup for apt-get
export DEBIAN_FRONTEND=noninteractive

# Check if modules exists
for module in ${BUILD_MODULES[@]}; do
	module_dir="/docker/scripts/modules/${module}"
	if [ ! -d "$module_dir" ]; then
		echo "Invalid module $module"
		exit 1
	fi
done

# Create dirs
mkdir -p /app/local

# Update and install base packages
apt-get update
apt-get install --no-install-recommends -y \
	ca-certificates \
	curl \
	gnupg

# Install required modules
for module in ${BUILD_MODULES[@]}; do
	script="/docker/scripts/modules/${module}/install"
	if [ -f "$script" ]; then
		echo "Installing $module"
		"$script"
	fi
done
