#!/bin/bash

add-apt-repository ppa:ondrej/php

# Check
if [ "$BUILD_PHP_VERSION" == "7.1" ]; then
	apt-get install --no-install-recommends -y php7.1-cli php7.1-fpm php7.1-zip
	mkdir -p /var/run/php
	ln -s /var/run/php/php7.1-fpm.sock /var/run/php/php-fpm.sock
else
	echo "PHP version not supported. $BUILD_PHP_VERSION"
	exit 1
fi

# Install composer
(cd /tmp && /docker/scripts/modules/php/get-composer && mv composer.phar /usr/local/bin/composer)